// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace SimpleBrush
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "SimpleBrush";
        public const string Version     = "1.0.0";
        public const string Title       = "SimpleBrush";
        public const string Description = "Unlock natural resource brushes and restore depleted resources.";
    }
}
