// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace SimpleRadio
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "SimpleRadio";
        public const string Version     = "1.0.2";
        public const string Title       = "SimpleRadio";
        public const string Description = "Simple Custom Radio - Drop OGG files and play";
    }
}
