// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace MapExt2
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "MapExt2";
        public const string Version     = "2.1.0";
        public const string Title       = "MapExt";
        public const string Description = "MapSize Extend 28/57/114km";
    }
}
