// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace EconomyEX
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "EconomyEX";
        public const string Version     = "1.2.2";
        public const string Title       = "EconomyEX";
        public const string Description = "Economy Extra Fix and Performance Boost";
    }
}
